spring:
  application:
    name: "tickethub_consumer"

  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER_ADDRESS}

kafka:
  createTicketMessageTopic: ${KAFKA_TOPIC_NAME}
  createTicketMessageGroup: ${KAFKA_CONSUMER_GROUP}


